version: "3.0"

server:
  address: "127.0.0.1"
  port: 50051
  mode: "server"
  timeout: "10s"

worker:
  defaultCpuLimit: 50              # 50% CPU for development
  defaultMemoryLimit: 256          # 256MB memory limit
  defaultIoLimit: 0                # No I/O limit
  maxConcurrentJobs: 5             # Small number for development
  jobTimeout: "30m"                # 30-minute job timeout
  cleanupTimeout: "2s"             # Quick cleanup
  validateCommands: true           # Enable command validation

security:
  tlsEnabled: false                # Disable TLS for local dev
  serverCertPath: "./certs/server-cert.pem"
  serverKeyPath: "./certs/server-key.pem"
  caCertPath: "./certs/ca-cert.pem"
  clientCertPath: "./certs/client-cert.pem"
  clientKeyPath: "./certs/client-key.pem"
  requireClientCert: false
  minTlsVersion: "1.3"

cgroup:
  baseDir: "/tmp/worker-dev-cgroups"  # Use temp for development
  namespaceMount: "/sys/fs/cgroup"
  enableControllers: [ "memory", "cpu" ] # Minimal controllers
  cleanupTimeout: "1s"

grpc:
  maxRecvMsgSize: 262144           # 256KB
  maxSendMsgSize: 1048576          # 1MB
  maxHeaderListSize: 524288        # 512KB
  keepAliveTime: "30s"
  keepAliveTimeout: "5s"

logging:
  level: "DEBUG"                   # Verbose logging for development
  format: "text"                   # Human-readable format
  output: "stdout"                 # Console output
