name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.21'

jobs:
  # Test and Code Quality
  test:
    name: Test and Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Run tests with coverage
        run: |
          go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: github.repository == 'ehsaniara/job-worker'
        with:
          files: ./coverage.out
          flags: unittests

  # Build Binaries
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: [ test ]
    
    strategy:
      matrix:
        goos: [ linux, darwin ]
        goarch: [ amd64, arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binaries
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # Create build directory
          mkdir -p build/${{ matrix.goos }}-${{ matrix.goarch }}
          
          # Build main server binary
          go build -ldflags="-w -s -X main.Version=${{ github.ref_name }} -X main.BuildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ) -X main.GitCommit=${{ github.sha }}" \
            -o build/${{ matrix.goos }}-${{ matrix.goarch }}/job-worker \
            ./cmd/server
          
          # Build CLI binary
          go build -ldflags="-w -s -X main.Version=${{ github.ref_name }} -X main.BuildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ) -X main.GitCommit=${{ github.sha }}" \
            -o build/${{ matrix.goos }}-${{ matrix.goarch }}/job-worker-cli \
            ./cmd/cli
          
          # Build job-init binary (Linux only)
          if [ "${{ matrix.goos }}" = "linux" ]; then
            go build -ldflags="-w -s" \
              -o build/${{ matrix.goos }}-${{ matrix.goarch }}/job-init \
              ./cmd/job-init
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/${{ matrix.goos }}-${{ matrix.goarch }}/

  # Release (only on tags)
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release
          
          # Create compressed archives for each platform
          for dir in artifacts/binaries-*/; do
            platform=$(basename "$dir" | sed 's/binaries-//')
            tar -czf "release/job-worker-${platform}.tar.gz" -C "$dir" .
          done
          
          # Generate checksums
          cd release
          sha256sum * > checksums.txt
          cd -

      - name: Generate release notes
        run: |
          echo "## What's Changed" > release_notes.md
          echo "" >> release_notes.md
          
          # Get commits since last tag
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            git log $LAST_TAG..HEAD --pretty=format:"* %s (%h)" >> release_notes.md
          else
            echo "* Initial release" >> release_notes.md
          fi
          
          echo "" >> release_notes.md
          echo "## Binaries" >> release_notes.md
          echo "Download the appropriate binary for your platform from the assets below." >> release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          body_path: release_notes.md
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          generate_release_notes: true